### ISSUE TITLE
1 Dimensional error when running regridding 

### ISSUE THREAD

**Issue by msleckman** [USGS-R/drb_gridmet_tools#4]
Getting the following error when running g2s.run_weights() on with the polygon file `nhru_02.shp`

`ValueError: shape mismatch: value array of shape (1, 15342) could not be broadcast to indexing result with 1 dimensions`

Overarching function found [gridmet_regridding()](https://github.com/USGS-R/drb_gridmet_tools/blob/ed0dd7517e54c3876a680953e2b8758eae95cae8/gridmet_split_script.py#L113) - error occuring at `L:152`

**Comment by jsadler2** [comment]
I am getting the same error, but it doesn't seem to be happening every time... 🤔
Here's the full traceback:
```
Traceback (most recent call last):
  File "/caldera/projects/usgs/water/impd/pump/gridmet/drb_gridmet_tools/gridmet_split_script.py", line 192, in <module>
    g2shp_regridding(xarray_dict= xarray_dict,
  File "/caldera/projects/usgs/water/impd/pump/gridmet/drb_gridmet_tools/gridmet_split_script.py", line 150, in g2shp_regridding
    g2s.run_weights()
  File "/home/jsadler/miniconda3/envs/gridmet_tools_IS/lib/python3.10/site-packages/grd2shp_xagg/grd2shp_xagg.py", line 293, in run_weights
    xr_agg = prep_for_nc(aggragated)
  File "/home/jsadler/miniconda3/envs/gridmet_tools_IS/lib/python3.10/site-packages/xagg/export.py", line 61, in prep_for_nc
    ds_out[var].loc[{'poly_idx':poly_idx}] = agg_obj.agg.loc[poly_idx,var][0]
  File "/home/jsadler/miniconda3/envs/gridmet_tools_IS/lib/python3.10/site-packages/xarray/core/dataarray.py", line 210, in __setitem__
    self.data_array[pos_indexers] = value
  File "/home/jsadler/miniconda3/envs/gridmet_tools_IS/lib/python3.10/site-packages/xarray/core/dataarray.py", line 762, in __setitem__
    self.variable[key] = value
  File "/home/jsadler/miniconda3/envs/gridmet_tools_IS/lib/python3.10/site-packages/xarray/core/variable.py", line 846, in __setitem__
    raise ValueError(
ValueError: shape mismatch: value array of shape (1, 2193) could not be broadcast to indexing result with 1 dimensions
```

**Comment by jsadler2** [comment]
I did some investigating and found that changing this line was a workaround (seems like there was an extra list level in the output for some reason (had to go from `[0]` to `[0][0]`:
old:
https://github.com/ks905383/xagg/blob/5015c7fb188dd2000aff592555dbaf90bc845262/xagg/export.py#L61
```
ds_out[var].loc[{'poly_idx':poly_idx}] = agg_obj.agg.loc[poly_idx,var][0]
```
new:
```
ds_out[var].loc[{'poly_idx':poly_idx}] = agg_obj.agg.loc[poly_idx,var][0][0]
```

**Comment by msleckman** [comment]
Thanks @rmcd-mscb for updated in xagg. 

Updated the `environment.yml` and replaced `-xagg` lib install with 
`pip: 
    - git+https://github.com/rmcd-mscb/xagg.git@nc_prep_fix` that pulls new version of updated version of xagg library with a fix.
